<a href="https://colab.research.google.com/github/bchanyoo/NLP/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#0차원 텐서(스칼라)
d = np.array(5)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 0
텐서의 크기(shape) : ()


In [3]:
#1차원 텐서(벡터)

d = np.array([1, 2, 3, 4])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 1
텐서의 크기(shape) : (4,)


In [4]:
#2차원 텐서(행렬, matrix)

d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


In [6]:
#3차원 텐서

d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print(d)
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [19 20 21 22 23]
  [23 24 25 26 27]]]
텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)
